// <auto-generated />
using System;
using AccessToBlazer.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AccessToBlazer.Web.Migrations
{
    [DbContext(typeof(SampleDbContext))]
    partial class SampleDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AccessToBlazer.Web.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("City")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers", (string)null);

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            City = "Springfield",
                            CustomerName = "Acme Corp",
                            Phone = "555-0101"
                        },
                        new
                        {
                            CustomerId = 2,
                            City = "Shelbyville",
                            CustomerName = "Globex Inc",
                            Phone = "555-0142"
                        },
                        new
                        {
                            CustomerId = 3,
                            City = "Austin",
                            CustomerName = "Initech",
                            Phone = "555-0177"
                        },
                        new
                        {
                            CustomerId = 4,
                            City = "Palo Alto",
                            CustomerName = "Hooli",
                            Phone = "555-0113"
                        },
                        new
                        {
                            CustomerId = 5,
                            City = "New York",
                            CustomerName = "Stark Industries",
                            Phone = "555-0190"
                        });
                });

            modelBuilder.Entity("AccessToBlazer.Web.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ProductId");

                    b.ToTable("Orders", (string)null);

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            CustomerId = 1,
                            OrderDate = new DateTime(2026, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 1,
                            Quantity = 10
                        },
                        new
                        {
                            OrderId = 2,
                            CustomerId = 1,
                            OrderDate = new DateTime(2026, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 4,
                            Quantity = 25
                        },
                        new
                        {
                            OrderId = 3,
                            CustomerId = 2,
                            OrderDate = new DateTime(2026, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 3,
                            Quantity = 2
                        },
                        new
                        {
                            OrderId = 4,
                            CustomerId = 3,
                            OrderDate = new DateTime(2026, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 5,
                            Quantity = 8
                        },
                        new
                        {
                            OrderId = 5,
                            CustomerId = 4,
                            OrderDate = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 6,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 6,
                            CustomerId = 5,
                            OrderDate = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 2,
                            Quantity = 12
                        });
                });

            modelBuilder.Entity("AccessToBlazer.Web.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UnitsInStock")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            ProductName = "Widget A",
                            UnitPrice = 9.99m,
                            UnitsInStock = 120
                        },
                        new
                        {
                            ProductId = 2,
                            ProductName = "Widget B",
                            UnitPrice = 14.50m,
                            UnitsInStock = 85
                        },
                        new
                        {
                            ProductId = 3,
                            ProductName = "Gadget X",
                            UnitPrice = 39.95m,
                            UnitsInStock = 40
                        },
                        new
                        {
                            ProductId = 4,
                            ProductName = "Gizmo Basic",
                            UnitPrice = 5.25m,
                            UnitsInStock = 300
                        },
                        new
                        {
                            ProductId = 5,
                            ProductName = "Gizmo Pro",
                            UnitPrice = 19.99m,
                            UnitsInStock = 150
                        },
                        new
                        {
                            ProductId = 6,
                            ProductName = "Turbo Chip",
                            UnitPrice = 79.00m,
                            UnitsInStock = 12
                        });
                });

            modelBuilder.Entity("AccessToBlazer.Web.Models.Order", b =>
                {
                    b.HasOne("AccessToBlazer.Web.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AccessToBlazer.Web.Models.Product", "Product")
                        .WithMany("Orders")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("AccessToBlazer.Web.Models.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("AccessToBlazer.Web.Models.Product", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
